server:
  port: 8080

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false

services:
  product-url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  user-url: ${USER_SERVICE_URL:http://localhost:8082}
  order-url: ${ORDER_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
